apiVersion: v1
kind: Service
metadata:
  name: transplaneur-server-hl
  labels:
    app: transplaneur-server
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: transplaneur-server
---
apiVersion: v1
kind: Service
metadata:
  name: transplaneur-server-api
  labels:
    app: transplaneur-server
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: http
  type: ClusterIP
  selector:
    app: transplaneur-server
---
apiVersion: v1
kind: Service
metadata:
  name: transplaneur-server-wireguard
  labels:
    app: transplaneur-server
spec:
  ports:
  - port: 51820
    name: wireguard
    protocol: UDP
    targetPort: wireguard
  type: LoadBalancer
  #type: NodePort
  selector:
    app: transplaneur-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transplaneur-server
  labels:
    app: transplaneur-server
spec:
  selector:
    matchLabels:
      app: transplaneur-server
  serviceName: transplaneur-server-hl
  replicas: 1
  template:
    metadata:
      labels:
        app: transplaneur-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        image: infrabuilder/transplaneur:edge
        imagePullPolicy: Always
        env:
        - name: BEARER_TOKEN
          value: "<REDACTED>"
        - name: WG_PRIVATE_KEY
          value: "<REDACTED>"
        - name: WG_ENDPOINT
          value: "<hostname>:51820"
        command: 
        - transplaneur
        - server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 51820
          name: wireguard
          protocol: UDP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi