apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: transplaneur-gateway
  labels:
    app: transplaneur-gateway
spec:
  selector:
    matchLabels:
      app: transplaneur-gateway
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: transplaneur-gateway
    spec:
      containers:
      - name: transplaneur-gateway
        image: infrabuilder/transplaneur:edge
        imagePullPolicy: Always
        command: 
        - transplaneur
        - gateway
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        env:
        - name: "API_ENDPOINT"
          value: "https://<hostname>"  # <=== This is the value that needs to be set
        - name: "BEARER_TOKEN"
          value: "<REDACTED>"          # <=== This is the value that needs to be set
        - name: CLUSTER_POD_CIDR
          value: ""                    # <=== This is the value that needs to be set
        - name: CLUSTER_SVC_CIDR
          value: ""                    # <=== This is the value that needs to be set

        # Following env vars are set by k8s
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: run
          mountPath: /var/run/transplaneur
      terminationGracePeriodSeconds: 10
      volumes:
      - name: run
        hostPath:
          path: /var/run/transplaneur
          type: DirectoryOrCreate