apiVersion: v1
kind: Pod
# ...
spec:
  # ...
  containers:
  # ...
  - name: transplaneur-sidecar
    command:
    - transplaneur
    - sidecar
    image: infrabuilder/transplaneur:edge
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 10m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/transplaneur
      readOnly: true
      name: run
  # ...
  volumes:
  - name: run
    hostPath:
      path: /var/run/transplaneur
      type: DirectoryOrCreate
